common:
  port: 8080 # порт, на котором будет запускаться наше приложение
postgres:
  database_url: postgresql://postgre:postgre@localhost/postgre
  require_ssl: false # стоит ли шифровать соединение с базой